// Objective-C API for talking to vpnapp/client-tunnel Go package.
//   gobind -lang=objc vpnapp/client-tunnel
//
// File is generated by gobind. Do not edit.

#ifndef __Tunnel_H__
#define __Tunnel_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class TunnelConnectConfig;
@class TunnelProbeResult;
@class TunnelRealityClientConfig;
@class TunnelStatsSnapshot;
@class TunnelTrafficStats;
@class TunnelTunnelStatus;
@protocol TunnelProtectSocket;
@class TunnelProtectSocket;
@protocol TunnelStatusCallback;
@class TunnelStatusCallback;

@protocol TunnelProtectSocket <NSObject>
- (BOOL)protect:(long)fd;
@end

@protocol TunnelStatusCallback <NSObject>
- (void)onStatusChanged:(NSString* _Nullable)statusJSON;
@end

/**
 * ConnectConfig is the configuration passed from the mobile app to establish a tunnel.
 */
@interface TunnelConnectConfig : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull serverAddress;
@property (nonatomic) long serverPort;
@property (nonatomic) NSString* _Nonnull protocol;
@property (nonatomic) NSString* _Nonnull userID;
@property (nonatomic) TunnelRealityClientConfig* _Nullable reality;
@end

/**
 * ProbeResult holds the result of probing a single server with a specific protocol.
 */
@interface TunnelProbeResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull serverAddress;
@property (nonatomic) NSString* _Nonnull protocol;
@property (nonatomic) int64_t latency;
@property (nonatomic) BOOL success;
@property (nonatomic) NSString* _Nonnull error;
@end

/**
 * RealityClientConfig holds client-side REALITY settings.
 */
@interface TunnelRealityClientConfig : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull publicKey;
@property (nonatomic) NSString* _Nonnull shortID;
@property (nonatomic) NSString* _Nonnull serverName;
@property (nonatomic) NSString* _Nonnull fingerprint;
@end

/**
 * StatsSnapshot is a JSON-serializable snapshot of current traffic stats.
 */
@interface TunnelStatsSnapshot : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) int64_t bytesUp;
@property (nonatomic) int64_t bytesDown;
@property (nonatomic) double speedUp;
@property (nonatomic) double speedDown;
@property (nonatomic) double durationSecs;
@end

/**
 * TrafficStats tracks bandwidth usage for the current session.
Updated by the tunnel and read by the native module for UI display.
 */
@interface TunnelTrafficStats : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewTrafficStats creates a new traffic stats tracker.
 */
- (nullable instancetype)init;
/**
 * AddDownload records downloaded bytes.
 */
- (void)addDownload:(int64_t)bytes;
/**
 * AddUpload records uploaded bytes.
 */
- (void)addUpload:(int64_t)bytes;
/**
 * Snapshot returns the current stats as a JSON string.
Called by the native module to update the UI speed indicators.
 */
- (NSString* _Nonnull)snapshot;
@end

/**
 * TunnelStatus holds the current state of the VPN tunnel.
 */
@interface TunnelTunnelStatus : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull state;
@property (nonatomic) NSString* _Nonnull serverAddr;
@property (nonatomic) NSString* _Nonnull protocol;
@property (nonatomic) int64_t connectedAt;
@property (nonatomic) int64_t bytesUp;
@property (nonatomic) int64_t bytesDown;
@property (nonatomic) NSString* _Nonnull error;
@end

/**
 * Connection states exposed to the mobile app via TurboModule events.
 */
FOUNDATION_EXPORT NSString* _Nonnull const TunnelStateConnected;
/**
 * Connection states exposed to the mobile app via TurboModule events.
 */
FOUNDATION_EXPORT NSString* _Nonnull const TunnelStateConnecting;
/**
 * Connection states exposed to the mobile app via TurboModule events.
 */
FOUNDATION_EXPORT NSString* _Nonnull const TunnelStateDisconnected;
/**
 * Connection states exposed to the mobile app via TurboModule events.
 */
FOUNDATION_EXPORT NSString* _Nonnull const TunnelStateDisconnecting;
/**
 * Connection states exposed to the mobile app via TurboModule events.
 */
FOUNDATION_EXPORT NSString* _Nonnull const TunnelStateError;
/**
 * Connection states exposed to the mobile app via TurboModule events.
 */
FOUNDATION_EXPORT NSString* _Nonnull const TunnelStateReconnecting;

/**
 * Connect establishes a VPN tunnel using the provided configuration JSON.
Blocks until the SOCKS5 proxy is listening or an error occurs.
The configJSON parameter is a JSON-serialized ConnectConfig.
Returns an error string (empty on success).
 */
FOUNDATION_EXPORT NSString* _Nonnull TunnelConnect(NSString* _Nullable configJSON);

/**
 * Disconnect tears down the active VPN tunnel.
 */
FOUNDATION_EXPORT NSString* _Nonnull TunnelDisconnect(void);

/**
 * GetStatus returns the current tunnel status as a JSON string.
 */
FOUNDATION_EXPORT NSString* _Nonnull TunnelGetStatus(void);

/**
 * GetTrafficStats returns current session traffic stats as JSON.
Exported for gomobile — called by the native module.
 */
FOUNDATION_EXPORT NSString* _Nonnull TunnelGetTrafficStats(void);

/**
 * NewTrafficStats creates a new traffic stats tracker.
 */
FOUNDATION_EXPORT TunnelTrafficStats* _Nullable TunnelNewTrafficStats(void);

/**
 * ProbeServers tests connectivity to multiple servers in parallel
and returns results sorted by latency (fastest first).

This is called by the React Native app's protocol prober service
to determine which protocol and server combination works best
for the user's current network conditions.

serversJSON: JSON array of server objects with "address" and "port" fields
Returns: JSON array of ProbeResult objects
 */
FOUNDATION_EXPORT NSString* _Nonnull TunnelProbeServers(NSString* _Nullable serversJSON);

/**
 * SetProtectCallback registers the socket protection callback.
Must be called before Connect() on Android. No-op on iOS.
 */
FOUNDATION_EXPORT void TunnelSetProtectCallback(id<TunnelProtectSocket> _Nullable cb);

/**
 * SetStatusCallback registers a callback that receives tunnel state changes.
 */
FOUNDATION_EXPORT void TunnelSetStatusCallback(id<TunnelStatusCallback> _Nullable cb);

/**
 * StartTun starts the tun2socks engine that bridges a TUN file descriptor
to the local SOCKS5 proxy opened by Connect().

fd: the TUN file descriptor from the OS VPN service
  - Android: VpnService.Builder.establish().getFd()
  - iOS: socketpair fd bridged to NEPacketTunnelFlow

Returns empty string on success, error message on failure.
Must be called AFTER Connect() has successfully started xray-core.
 */
FOUNDATION_EXPORT NSString* _Nonnull TunnelStartTun(long fd);

/**
 * StopTun stops the tun2socks engine.
Should be called before Disconnect() to cleanly shut down.
 */
FOUNDATION_EXPORT NSString* _Nonnull TunnelStopTun(void);

@class TunnelProtectSocket;

@class TunnelStatusCallback;

/**
 * ProtectSocket is implemented by the Android VpnService to prevent
the tunnel's own sockets from being routed through the VPN (routing loop).

gomobile generates a Java interface: tunnel.ProtectSocket
The Android TunnelVpnService implements it by calling VpnService.protect(fd).

On iOS this is not needed — the Network Extension process is exempt
from its own tunnel by default.
 */
@interface TunnelProtectSocket : NSObject <goSeqRefInterface, TunnelProtectSocket> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)protect:(long)fd;
@end

/**
 * StatusCallback is implemented by the native module (iOS/Android) to receive
tunnel state changes. gomobile will generate the appropriate interface binding.
 */
@interface TunnelStatusCallback : NSObject <goSeqRefInterface, TunnelStatusCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onStatusChanged:(NSString* _Nullable)statusJSON;
@end

#endif
