package model

import "time"

// LinkCode is a short-lived 6-digit numeric code that allows a friend's
// device to claim a slot under an existing plan owner's account.
//
// The code is generated by POST /devices/share-code (auth required) and
// consumed by POST /auth/link (no auth — the caller is a brand-new device
// that doesn't yet have a token for the target account).
type LinkCode struct {
	Code      string    `gorm:"primaryKey;type:varchar(6)" json:"code"`
	UserID    string    `gorm:"not null;index" json:"user_id"`
	CreatedAt time.Time `gorm:"autoCreateTime" json:"created_at"`
	ExpiresAt time.Time `gorm:"not null;index" json:"expires_at"`
}

// TableName overrides GORM's default pluralization.
func (LinkCode) TableName() string { return "link_codes" }
